server: "hub-cloud.browserstack.com"
user: "BROWSERSTACK_USERNAME"
key: "BROWSERSTACK_ACCESS_KEY"

common_caps:
  "build": "rspec-browserstack"
  # "build": "cart2"
  "browserstack.debug": true

browser_caps:
  -
    "os":         "OS X"
    "os_version": "High Sierra"
    "browser":    "Chrome"
    # "browser_version":    "62.0"
    # "resolution": "1024*768"
    # "device": "iPhone 7"
    # "realMobile": "true"
    # "os_version": "10.0"
