# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c61d9227f69d859a879731ce9abb23f45e7087f3604d977ea5b37d11dd5f2b85185124d3e46e4a67bb14383bfd57ee13c85fb8a4473a18dc9079f95fd0c9fed8

test:
  secret_key_base: 764c4e3e2e3563b222f8f5d7817c9a19baf3fea2e16bc00c4533755b6eb4734b08512d9d9be6bf8a7cf4e2bab17fdbbb84dcd425624513a946283bd1348de5bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
