# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e705e912aaa1b0b40396e4343436cf46598699c381fbc919244bbd94a184d71433a772fe990d7b4767746876bec84a9e2d2f11d9c03b8b946efed6e04134ab3

  #E-xact's Payment Page Demo - Receipt Only
  ex_hco1_id: WSP-ROVI-Xi1zHAAdvw
  ex_hco1_tk: iNmlgZ2lQJtcp2zUl2DI

  #E-xact's Payment Page Demo - Silent Post
  ex_hco2_id: HCO-ROVI-940
  ex_hco2_tk: GZn3ZX4RyB9owMAjJz4J

  #E-xact's Payment Page Demo - Values Received
  ex_hco3_id: WSP-ROVI-Nbf&pgAdwA
  ex_hco3_tk: atswkim3iq~lQawjLDnq

  #PayEezy's Payment Page Demo - Values Received
  fd_hco1_id: HCO-R0V1-817
  fd_hco1_tk: f8~bGdU4u159KiQKVfca


test:
  secret_key_base: 3dbb3919bcb3b2c40f26762a11e80ba0b1c43cc86a2fc2ebb65fe06976d69026bc87ca9955fc1518b93d151621316f17ea3a8d6138ebdcce0b22c91cb68e23fb

  #E-xact's Payment Page Demo - Receipt Only
  ex_hco1_id: WSP-ROVI-Xi1zHAAdvw
  ex_hco1_tk: iNmlgZ2lQJtcp2zUl2DI

  #E-xact's Payment Page Demo - Silent Post
  ex_hco2_id: HCO-ROVI-940
  ex_hco2_tk: GZn3ZX4RyB9owMAjJz4J

  #E-xact's Payment Page Demo - Values Received
  ex_hco3_id: WSP-ROVI-Nbf&pgAdwA
  ex_hco3_tk: atswkim3iq~lQawjLDnq

  #PayEezy's Payment Page Demo - Values Received
  fd_hco1_id: HCO-R0V1-817
  fd_hco1_tk: f8~bGdU4u159KiQKVfca

###################################################
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

  #E-xact's Payment Page Demo - Receipt Only
  ex_hco1_id: <%= ENV["EX_HCO1_ID"] %>
  ex_hco1_tk: <%= ENV["EX_HCO1_TK"] %>

  #E-xact's Payment Page Demo - Silent Post
  ex_hco2_id: <%= ENV["EX_HCO2_ID"] %>
  ex_hco2_tk: <%= ENV["EX_HCO2_TK"] %>

  #E-xact's Payment Page Demo - Values Received
  ex_hco3_id: <%= ENV["EX_HCO3_ID"] %>
  ex_hco3_tk: <%= ENV["EX_HCO3_TK"] %>

  #PayEezy's Payment Page Demo - Values Received
  fd_hco1_id: <%= ENV["FD_HCO1_ID"] %>
  fd_hco1_tk: <%= ENV["FD_HCO1_TK"] %>
