# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
    secret_key_base: <%= ENV["SECRET_KEY_BASE_DEV"] %>

    #E-xact's Payment Page Demo - Receipt Only
    ex_hco1_id: <%= ENV["EX_HCO1_ID"] %>
    ex_hco1_tk: <%= ENV["EX_HCO1_TK"] %>

    #E-xact's Payment Page Demo - Silent Post
    ex_hco2_id: <%= ENV["EX_HCO2_ID"] %>
    ex_hco2_tk: <%= ENV["EX_HCO2_TK"] %>

    #E-xact's Payment Page Demo - Values Received
    ex_hco3_id: <%= ENV["EX_HCO3_ID"] %>
    ex_hco3_tk: <%= ENV["EX_HCO3_TK"] %>

    #E-xact's Payment Page - QA
    ex_hco4_id: <%= ENV["EX_HCO4_ID"] %>
    ex_hco4_tk: <%= ENV["EX_HCO4_TK"] %>

    #E-xact's Payment Page - QA - Cineplex
    ex_hco5_id: <%= ENV["EX_HCO5_ID"] %>
    ex_hco5_tk: <%= ENV["EX_HCO5_TK"] %>

    #PayEezy's Payment Page Demo - Values Received
    fd_hco1_id: <%= ENV["FD_HCO1_ID"] %>
    fd_hco1_tk: <%= ENV["FD_HCO1_TK"] %>

    #PayEezy's Payment Page Prod - Receipt Only
    fd_hco2_id: <%= ENV["FD_HCO2_ID"] %>
    fd_hco2_tk: <%= ENV["FD_HCO2_TK"] %>

    #PayEezy's Payment Page QA - Receipt Only
    fd_hco3_id: <%= ENV["FD_HCO3_ID"] %>
    fd_hco3_tk: <%= ENV["FD_HCO3_TK"] %>
    fd_hco3_rep: <%= ENV["FD_HCO3_REP"] %>
    fd_hco3_reb: <%= ENV["FD_HCO3_REB"] %>

    #PayEezy's Payment Page QA - Receipt Only
    fd_hco3_vanilla_id: <%= ENV["FD_HCO3_VANILLA_ID"] %>
    fd_hco3_vanilla_tk: <%= ENV["FD_HCO3_VANILLA_TK"] %>

    #PayEezy's Payment Page FT2 - Receipt Only
    fd_hco4_id: <%= ENV["FD_HCO4_ID"] %>
    fd_hco4_tk: <%= ENV["FD_HCO4_TK"] %>

    #PayEezy's Payment Page FT1 - Receipt Only
    fd_hco5_id: <%= ENV["FD_HCO5_ID"] %>
    fd_hco5_tk: <%= ENV["FD_HCO5_TK"] %>

    #PayEezy's Payment Page CAT - Receipt Only
    fd_hco6_id: <%= ENV["FD_HCO6_ID"] %>
    fd_hco6_tk: <%= ENV["FD_HCO6_TK"] %>

    #PayEezy's Payment Page CERT
    fd_hco7_id: <%= ENV["FD_HCO7_ID"] %>
    fd_hco7_tk: <%= ENV["FD_HCO7_TK"] %>

    #Admin password for Heroku app (Cucumber tests)
    admin_user:     <%= ENV["ADMIN_USR"] %>
    admin_password: <%= ENV["ADMIN_PSW"] %>

    #Regular password for Heroku app (Cucumber tests)
    reg_user:     <%= ENV["REG_USR"] %>
    reg_password: <%= ENV["REG_PSW"] %>

    #Admin password for Heroku app (Cucumber tests)
    admin_user:     <%= ENV["ADMIN_USR"] %>
    admin_password: <%= ENV["ADMIN_PSW"] %>

    #Regular password for Heroku app (Cucumber tests)
    reg_user:     <%= ENV["REG_USR"] %>
    reg_password: <%= ENV["REG_PSW"] %>


test:
    secret_key_base: <%= ENV["SECRET_KEY_BASE_TEST"] %>

    #E-xact's Payment Page Demo - Receipt Only
    ex_hco1_id: <%= ENV["EX_HCO1_ID"] %>
    ex_hco1_tk: <%= ENV["EX_HCO1_TK"] %>

    #E-xact's Payment Page Demo - Silent Post
    ex_hco2_id: <%= ENV["EX_HCO2_ID"] %>
    ex_hco2_tk: <%= ENV["EX_HCO2_TK"] %>

    #E-xact's Payment Page Demo - Values Received
    ex_hco3_id: <%= ENV["EX_HCO3_ID"] %>
    ex_hco3_tk: <%= ENV["EX_HCO3_TK"] %>

    #E-xact's Payment Page - QA
    ex_hco4_id: <%= ENV["EX_HCO4_ID"] %>
    ex_hco4_tk: <%= ENV["EX_HCO4_TK"] %>

    #E-xact's Payment Page - QA - Cineplex
    ex_hco5_id: <%= ENV["EX_HCO5_ID"] %>
    ex_hco5_tk: <%= ENV["EX_HCO5_TK"] %>

    #PayEezy's Payment Page Demo - Values Received
    fd_hco1_id: <%= ENV["FD_HCO1_ID"] %>
    fd_hco1_tk: <%= ENV["FD_HCO1_TK"] %>

    #PayEezy's Payment Page Prod - Receipt Only
    fd_hco2_id: <%= ENV["FD_HCO2_ID"] %>
    fd_hco2_tk: <%= ENV["FD_HCO2_TK"] %>

    #PayEezy's Payment Page QA - Receipt Only
    fd_hco3_id: <%= ENV["FD_HCO3_ID"] %>
    fd_hco3_tk: <%= ENV["FD_HCO3_TK"] %>
    fd_hco3_rep: <%= ENV["FD_HCO3_REP"] %>
    fd_hco3_reb: <%= ENV["FD_HCO3_REB"] %>

    #PayEezy's Payment Page QA - Receipt Only
    fd_hco3_vanilla_id: <%= ENV["FD_HCO3_VANILLA_ID"] %>
    Fd_hco3_vanilla_tk: <%= ENV["FD_HCO3_VANILLA_TK"] %>

    #PayEezy's Payment Page FT2 - Receipt Only
    fd_hco4_id: <%= ENV["FD_HCO4_ID"] %>
    fd_hco4_tk: <%= ENV["FD_HCO4_TK"] %>

    #PayEezy's Payment Page FT1 - Receipt Only
    fd_hco5_id: <%= ENV["FD_HCO5_ID"] %>
    fd_hco5_tk: <%= ENV["FD_HCO5_TK"] %>

    #PayEezy's Payment Page CAT - Receipt Only
    fd_hco6_id: <%= ENV["FD_HCO6_ID"] %>
    fd_hco6_tk: <%= ENV["FD_HCO6_TK"] %>

    #PayEezy's Payment Page CERT
    fd_hco7_id: <%= ENV["FD_HCO7_ID"] %>
    fd_hco7_tk: <%= ENV["FD_HCO7_TK"] %>

    #Admin password for Heroku app (Cucumber tests)
    admin_user:     <%= ENV["ADMIN_USR"] %>
    admin_password: <%= ENV["ADMIN_PSW"] %>

    #Regular password for Heroku app (Cucumber tests)
    reg_user:     <%= ENV["REG_USR"] %>
    reg_password: <%= ENV["REG_PSW"] %>

###################################################
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_PROD"] %>

  #E-xact's Payment Page Demo - Receipt Only
  ex_hco1_id: <%= ENV["EX_HCO1_ID"] %>
  ex_hco1_tk: <%= ENV["EX_HCO1_TK"] %>

  #E-xact's Payment Page Demo - Silent Post
  ex_hco2_id: <%= ENV["EX_HCO2_ID"] %>
  ex_hco2_tk: <%= ENV["EX_HCO2_TK"] %>

  #E-xact's Payment Page Demo - Values Received
  ex_hco3_id: <%= ENV["EX_HCO3_ID"] %>
  ex_hco3_tk: <%= ENV["EX_HCO3_TK"] %>

  #E-xact's Payment Page - QA
  ex_hco4_id: <%= ENV["EX_HCO4_ID"] %>
  ex_hco4_tk: <%= ENV["EX_HCO4_TK"] %>

  #E-xact's Payment Page - QA - Cineplex
  ex_hco5_id: <%= ENV["EX_HCO5_ID"] %>
  ex_hco5_tk: <%= ENV["EX_HCO5_TK"] %>

  #PayEezy's Payment Page Demo - Values Received
  fd_hco1_id: <%= ENV["FD_HCO1_ID"] %>
  fd_hco1_tk: <%= ENV["FD_HCO1_TK"] %>

  #PayEezy's Payment Page Prod - Receipt Only
  fd_hco2_id: <%= ENV["FD_HCO2_ID"] %>
  fd_hco2_tk: <%= ENV["FD_HCO2_TK"] %>

  #PayEezy's Payment Page QA - Receipt Only
  fd_hco3_id: <%= ENV["FD_HCO3_ID"] %>
  fd_hco3_tk: <%= ENV["FD_HCO3_TK"] %>
  fd_hco3_rep: <%= ENV["FD_HCO3_REP"] %>
  fd_hco3_reb: <%= ENV["FD_HCO3_REB"] %>

  #PayEezy's Payment Page QA - Receipt Only
  fd_hco3_vanilla_id: <%= ENV["FD_HCO3_VANILLA_ID"] %>
  fd_hco3_vanilla_tk: <%= ENV["FD_HCO3_VANILLA_TK"] %>

  #PayEezy's Payment Page FT2 - Receipt Only
  fd_hco4_id: <%= ENV["FD_HCO4_ID"] %>
  fd_hco4_tk: <%= ENV["FD_HCO4_TK"] %>

  #PayEezy's Payment Page FT1 - Receipt Only
  fd_hco5_id: <%= ENV["FD_HCO5_ID"] %>
  fd_hco5_tk: <%= ENV["FD_HCO5_TK"] %>

  #PayEezy's Payment Page CAT - Receipt Only
  fd_hco6_id: <%= ENV["FD_HCO6_ID"] %>
  fd_hco6_tk: <%= ENV["FD_HCO6_TK"] %>

  #PayEezy's Payment Page CERT
  fd_hco7_id: <%= ENV["FD_HCO7_ID"] %>
  fd_hco7_tk: <%= ENV["FD_HCO7_TK"] %>

  #Admin password for Heroku app (Cucumber tests)
  admin_user:     <%= ENV["ADMIN_USR"] %>
  admin_password: <%= ENV["ADMIN_PSW"] %>

  #Regular password for Heroku app (Cucumber tests)
  reg_user:     <%= ENV["REG_USR"] %>
  reg_password: <%= ENV["REG_PSW"] %>
